### PR TITLE
Updating code style for plus editor to better align with theme colors

### PR DESCRIPTION
**Pull request by bbende**

### CODE REVIEW

**Comment by atmoio** [comment]
Thank you!

**Comment by atmoio** [comment]
Should have added by the way that you need to build .scss files :) I'll do this myself and push it up. Should add instructions to the repo..

```
npm install
grunt
```

**Comment by bbende** [comment]
Ah sorry, I had done that when testing the change, but forget when I created the PR branch.

I updated my Futura theme in the desktop app and I can tell the code style change took effect, but for some reason the extensions page shows an error:

sn-extensions-error

I tried restarting and also uninstalling/reinstalling the theme, it still installs and has the updated style but shows this error. Could also be something I screwed up locally from testing my own customized version of the theme.

**Comment by atmoio** [comment]
Ah, forgot to update the package.json file. Should be fixed now.

**Pull request merged**
